workflows:
  build-android:
    triggering:
      events:
        - "push"
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
    name: Build Android app
    scripts:
      - flutter pub get
      - cat .env >> $CM_ENV
      - echo $PACKAGE_NAME
      - envsubst < flutter_native_splash.env.yaml > flutter_native_splash.yaml
      - dart run flutter_native_splash:create --path=./flutter_native_splash.yaml
      - envsubst < flutter_launcher_icon.env.yaml > flutter_launcher_icon.yaml
      - flutter pub run flutter_launcher_icons -f flutter_launcher_icon.yaml
      - flutter build apk
    artifacts:
      - build/**/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - abdealex05@gmail.com
