workflows:
  build-iOS:
    triggering:
      events:
        - "push"
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      # ios_signing:
      #   distribution_type: app_store
      #   bundle_identifier: com.keyspire.ts
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
    name: Build iOS app
    scripts:
      - flutter pub get
      - cat .env >> $CM_ENV
      - echo $PACKAGE_NAME
      - envsubst < pubspec.env.yaml > pubspec.yaml
      - dart run flutter_native_splash:create
      - dart run flutter_launcher_icons
      - flutter pub global activate rename
      - rename setAppName --targets ios,android --value $APP_NAME
      - rename setBundleId --targets ios,android --value $PACKAGE_NAME
      - flutter build ipa
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - abdealex05@gmail.com
